SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS tasks;
CREATE TABLE tasks (
  id INT(11) NOT NULL AUTO_INCREMENT,
  status VARCHAR(100) NOT NULL,
  timestamp VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
  )  ENGINE=InnoDB CHARSET=utf8;
  
SET FOREIGN_KEY_CHECKS = 1;